name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Locale
      run: |
        sudo locale-gen id_ID.UTF-8
        sudo update-locale LANG=id_ID.UTF-8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy App
      run: |
        streamlit run app.py
